[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "rust port of babel and closure compiler."
documentation = "https://rustdoc.swc.rs/swc_ecma_transforms/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_ecma_transforms"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.227.21"

  [package.metadata.docs.rs]
  all-features = true
  rustdoc-args = ["--cfg", "docsrs"]

[lib]
bench = false

[features]
compat = ["swc_ecma_transforms_compat"]
concurrent = [
  "swc_ecma_transforms_compat/concurrent",
  "swc_ecma_transforms_optimization/concurrent",
  "swc_ecma_transforms_react/concurrent",
]
module = ["swc_ecma_transforms_module"]
multi-module-decorator = ["swc_ecma_transforms_proposal/multi-module"]
optimization = ["swc_ecma_transforms_optimization"]
proposal = ["swc_ecma_transforms_proposal"]
react = ["swc_ecma_transforms_react"]
typescript = ["swc_ecma_transforms_typescript"]

[dependencies]
swc_atoms                        = { version = "0.6.5", path = "../swc_atoms" }
swc_common                       = { version = "0.33.13", path = "../swc_common" }
swc_ecma_ast                     = { version = "0.110.18", path = "../swc_ecma_ast" }
swc_ecma_transforms_base         = { version = "0.135.13", path = "../swc_ecma_transforms_base" }
swc_ecma_transforms_compat       = { version = "0.161.18", path = "../swc_ecma_transforms_compat", optional = true }
swc_ecma_transforms_module       = { version = "0.178.20", path = "../swc_ecma_transforms_module", optional = true }
swc_ecma_transforms_optimization = { version = "0.196.20", path = "../swc_ecma_transforms_optimization", optional = true }
swc_ecma_transforms_proposal     = { version = "0.169.18", path = "../swc_ecma_transforms_proposal", optional = true }
swc_ecma_transforms_react        = { version = "0.181.20", path = "../swc_ecma_transforms_react", optional = true }
swc_ecma_transforms_typescript   = { version = "0.186.20", path = "../swc_ecma_transforms_typescript", optional = true }
swc_ecma_utils                   = { version = "0.125.5", path = "../swc_ecma_utils" }
swc_ecma_visit                   = { version = "0.96.18", path = "../swc_ecma_visit" }

[dev-dependencies]
pretty_assertions = "1.3"
sourcemap         = "6.2"
tempfile          = "3"

swc_ecma_codegen            = { version = "0.146.56", path = "../swc_ecma_codegen" }
swc_ecma_parser             = { version = "0.141.37", path = "../swc_ecma_parser" }
swc_ecma_transforms_testing = { version = "0.138.13", path = "../swc_ecma_transforms_testing" }
testing                     = { version = "0.35.15", path = "../testing" }
